// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJN1upg-0ppe2u5YocSBewifkh5uKF9s',
    appId: '1:32983595944:web:ce6af1da179ffc8b44bb9d',
    messagingSenderId: '32983595944',
    projectId: 'musica-216ef',
    authDomain: 'musica-216ef.firebaseapp.com',
    storageBucket: 'musica-216ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrLjsGwUCSkSzbu91X-6PAWg76PItWAVs',
    appId: '1:32983595944:android:554f557149d69a8844bb9d',
    messagingSenderId: '32983595944',
    projectId: 'musica-216ef',
    storageBucket: 'musica-216ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwV6v2Q__22ed11Rkm1Wyz6aba0jKn2vk',
    appId: '1:32983595944:ios:00e54f47a4b5aeb044bb9d',
    messagingSenderId: '32983595944',
    projectId: 'musica-216ef',
    storageBucket: 'musica-216ef.firebasestorage.app',
    iosBundleId: 'com.example.firecrud5b25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaJN1upg-0ppe2u5YocSBewifkh5uKF9s',
    appId: '1:32983595944:web:6beaa02d5061485e44bb9d',
    messagingSenderId: '32983595944',
    projectId: 'musica-216ef',
    authDomain: 'musica-216ef.firebaseapp.com',
    storageBucket: 'musica-216ef.firebasestorage.app',
  );

}